// <auto-generated />
namespace LetsShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LSP39 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LSP39));
        
        string IMigrationMetadata.Id
        {
            get { return "201809011149473_LSP3.9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
